//! Connections among **fixed-point types** — Q-format wrappers from
//! the [`fixed`] crate, std primitive integers (interpreted as
//! Q*N*.0 fixed-point), and [`core::num::NonZero<T>`] (punctured
//! Q*N*.0). The float/fixed split between [`crate::float`] and this
//! module is the crate's only top-level domain distinction:
//! everything finite-precision-with-integer-storage lives here;
//! every IEEE-binary type lives in [`crate::float`].
//!
//! [`fixed`]: https://docs.rs/fixed
//! [`core::num::NonZero<T>`]: https://doc.rust-lang.org/core/num/struct.NonZero.html
//!
//! - [`mod@i8`] / [`mod@i16`] / [`mod@i32`] / [`mod@i64`] / [`mod@i128`] —
//!   Conns landing on signed `iN` and `FixedI<N><Frac>`. Per the
//!   right-side-wins module rule, each per-primitive submodule hosts
//!   the Conn consts where that primitive type (or its Q-format
//!   wrapper) wins as the destination.
//! - [`mod@u8`] / [`mod@u16`] / [`mod@u32`] / [`mod@u64`] / [`mod@u128`] —
//!   same shape over unsigned `uN` and `FixedU<N><Frac>`.
//!
//! ## Conn-name prefix conventions (post-merge)
//!
//! After the `int/` ⊕ `fixed/` merge, the prefix letter alone tells
//! you which world a side belongs to:
//!
//! | Prefix | Shape | Side meaning                                            |
//! |--------|-------|---------------------------------------------------------|
//! | `Q`    | 1L+3D | `FixedI<N>` / `FixedU<N>` (Q-format). Sign implicit by module path; digits = frac bits. |
//! | `I`    | 1L+3D | signed std primitive (`iN`). Digits = bit-width.        |
//! | `U`    | 1L+3D | unsigned std primitive (`uN`). Digits = bit-width.      |
//! | `N`    | 1L+3D | `NonZero<iN>` / `NonZero<uN>`. Sign implicit by module path; digits = bit-width. |
//!
//! Cross-module name collisions (e.g. `Q008Q004` in both
//! [`mod@i8`] and [`mod@u8`]) are allowed and resolved by qualified
//! import.
//!
//! ## Macros
//!
//! Seven macro families generate the std-int Conns; all live in this
//! parent module and are `pub(crate)`-imported by the per-primitive
//! submodules:
//!
//! | macro | direction | Galois | constructor |
//! |---|---|---|---|
//! | `uint_uint!`        | U→U widening    | left  | `new_left` |
//! | `int_uint!`         | I→U widening    | left  | `new_left` |
//! | `ext_int!`          | I→I, U→I widening (Extended source) | full triple | `new` |
//! | `int_int_narrow!`   | I→I narrowing   | left  | `new_left` |
//! | `uint_uint_narrow!` | U→U narrowing   | left  | `new_left` |
//! | `int_uint_narrow!`  | I→U narrowing   | left  | `new_left` |
//! | `uint_int_sat!`     | U→I non-widening | right | `new_right` |
//!
//! The four narrowing/non-widening macros use a **FINE_MAX
//! boundary fixup** in `inner` (`inner(Coarse::MAX) =
//! Source::MAX`) so the relevant Galois bi-implication holds at
//! the source-side saturation plateau — same pattern as the
//! per-primitive `fix_fix_uN!` macros below. The right-Galois
//! `uint_int_sat!` macro doesn't need the fixup: its plateau lives
//! on the target side (negative `i_N` values clip to `0_u_M` via
//! `inner`), and `floor` collapses the symmetric way at the high
//! end.
//!
//! The intra-`fixed`-crate Conns are generated by per-primitive
//! `fix_fix_iN!` / `fix_fix_uN!` macros, each defined locally in its
//! per-host-type submodule (`fixed/i8.rs` etc.).
//!
//! The `fixed`-crate `FixedI<N><F>` / `FixedU<N><F>` types already
//! derive `PartialEq` / `Eq` / `PartialOrd` / `Ord` upstream —
//! totally ordered by their underlying integer bits — so they flow
//! through any `T: Eq + PartialOrd` law predicate without per-crate
//! impls.

// The macros expand at the call site (in each submodule), so this
// parent file doesn't need to import `Conn` or `Extended` itself —
// the submodules pull them in.

// ── std-int macros (lifted from former src/int.rs) ─────────────────

/// `Conn<u_N, u_M>` widening (`bits(u_N) < bits(u_M)`).
///
/// `ceil` is the lossless `as`-upcast; `inner` saturates targets
/// above `u_N::MAX` down to `u_N::MAX` before downcasting.
macro_rules! uint_uint {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating cast.")]
        pub const $NAME: Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                x as $B
            }
            fn inner(x: $B) -> $A {
                let cap = <$A>::MAX as $B;
                let clipped = if x > cap { cap } else { x };
                clipped as $A
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use uint_uint;

/// `Conn<i_N, u_M>` widening or same-width cross-sign
/// (`bits(i_N) ≤ bits(u_M)`).
///
/// `ceil` clips negatives to `0` then upcasts (lossless on the
/// non-negative half by the bit-width constraint); `inner`
/// saturates targets above `i_N::MAX` down to `i_N::MAX`.
macro_rules! int_uint {
    ($NAME:ident, $A:ty, $B:ty) => {
        // rustfmt's indent-instability bug with `#[doc = concat!(...)]`
        // means each fmt round pushes the args further right.
        // `#[rustfmt::skip]` pins the layout. See ext_int! below for
        // the same workaround.
#[rustfmt::skip]
        #[doc = concat!(
            "`",
            stringify!($A),
            " → ",
            stringify!($B),
            "` saturating cast: negatives clip to 0; `inner` saturates at source max."
        )]
        pub const $NAME: Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x < 0 { 0 } else { x as $B }
            }
            fn inner(x: $B) -> $A {
                let cap = <$A>::MAX as $B;
                let clipped = if x > cap { cap } else { x };
                clipped as $A
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use int_uint;

/// `Conn<Extended<$A>, $B>` widening with Extended source.
/// Covers both `I??I??` (signed widening) and `U??I??`
/// (unsigned-into-signed widening) — the body is identical, only
/// the source's `MIN`/`MAX` differ.
///
/// Constraints (verified at the call site, not at compile time):
/// - `(<$A>::MIN as $B) - 1` and `(<$A>::MAX as $B) + 1` must fit
///   in `$B` — guaranteed by `bits($A) < bits($B)` (signed source)
///   or `bits($A) ≤ bits($B) - 1` (unsigned source, equivalent).
/// - `<$B>::MIN < BELOW` and `<$B>::MAX > ABOVE` (i.e. target has
///   room beyond the source range so saturation values are
///   distinct).
macro_rules! ext_int {
    ($NAME:ident, $A:ty, $B:ty) => {
#[rustfmt::skip]
        #[doc = concat!(
            "`Extended<",
            stringify!($A),
            "> → ",
            stringify!($B),
            "` adjoint triple."
        )]
        pub const $NAME: Conn<Extended<$A>, $B> = {
            // `BELOW` is one below the source's MIN; `ABOVE` is one
            // above the source's MAX. Both are themselves in the
            // infinity regions: `inner(BELOW) == NegInf` and
            // `inner(ABOVE) == PosInf` (the `<=` / `>=` are
            // inclusive). `Finite(_)` only covers the open interval
            // `(BELOW, ABOVE)`.
            const BELOW: $B = (<$A>::MIN as $B) - 1;
            const ABOVE: $B = (<$A>::MAX as $B) + 1;
            fn ceil(x: Extended<$A>) -> $B {
                match x {
                    Extended::NegInf => <$B>::MIN,
                    Extended::Finite(a) => a as $B,
                    Extended::PosInf => ABOVE,
                }
            }
            fn inner(x: $B) -> Extended<$A> {
                if x <= BELOW {
                    Extended::NegInf
                } else if x >= ABOVE {
                    Extended::PosInf
                } else {
                    Extended::Finite(x as $A)
                }
            }
            fn floor(x: Extended<$A>) -> $B {
                match x {
                    Extended::NegInf => BELOW,
                    Extended::Finite(a) => a as $B,
                    Extended::PosInf => <$B>::MAX,
                }
            }
            Conn::new(ceil, inner, floor)
        };
    };
}
pub(crate) use ext_int;

// ── Narrowing macros ───────────────────────────────────────────────

/// `Conn<i_N, i_M>` narrowing (`bits(i_N) > bits(i_M)`).
///
/// **Constraint** (verified at the call site, not at compile time):
/// `bits($A) > bits($B)`. The macro's `ceil` casts `<$B>::MAX as $A`
/// and `<$B>::MIN as $A` for its threshold checks; both must fit
/// losslessly in `$A` for the saturation logic to be correct.
/// Mirrors the `ext_int!` constraint a few lines up.
///
/// `ceil` saturates at both `i_M::MIN` and `i_M::MAX`; `inner` is
/// the lossless widen with the high-end FINE_MAX fixup
/// (`inner(i_M::MAX) = i_N::MAX`).
///
/// **Why no FINE_MIN fixup?** The low-end plateau holds for
/// `galois_l` without one. The plateau covers source values
/// `a < i_M::MIN as i_N` (everything `ceil` collapses onto
/// `i_M::MIN`). For these, `ceil(a) = i_M::MIN ≤ b` is true for
/// every `b ∈ i_M`, so the law's LHS is always true, and the RHS
/// (`a ≤ inner(b)`) is also always true because
/// `inner(b) ≥ i_M::MIN as i_N > a` (since
/// `i_M::MIN as i_N > i_N::MIN ≥ a` by the bit-width
/// constraint). Both sides match without fiddling. Compare the
/// high end, where `ceil` collapsing onto `i_M::MAX` does require
/// the fixup so `a ≤ inner(i_M::MAX) = i_N::MAX` holds.
macro_rules! int_int_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else if x < <$B>::MIN as $A {
                    <$B>::MIN
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use int_int_narrow;

/// `Conn<u_N, u_M>` narrowing (`bits(u_N) > bits(u_M)`).
///
/// `ceil` saturates source values above `u_M::MAX` down to
/// `u_M::MAX` before downcasting. There is **no** low-end branch
/// (no `MIN` saturation arm) because both endpoints are unsigned —
/// the source range starts at `0 = u_N::MIN ≥ u_M::MIN = 0`, so no
/// source value can fall below the target's minimum. Compare
/// `int_int_narrow!`, which needs both arms because signed sources
/// can dip below the target's `MIN`.
///
/// `inner` is the lossless `as`-widen with a FINE_MAX fixup
/// (`inner(u_M::MAX) = u_N::MAX`). The fixup is required for
/// left-Galois to hold at the source-side saturation plateau
/// (mirrors the same pattern in the per-primitive `fix_fix_uN!`
/// macros).
macro_rules! uint_uint_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use uint_uint_narrow;

/// `Conn<u_N, i_M>` non-widening cross-sign (`bits(u_N) ≥ bits(i_M)`).
///
/// **Constraint** (verified at the call site, not at compile time):
/// `bits($A) ≥ bits($B)`. `floor` casts `<$B>::MAX as $A`, which
/// must fit in `$A` losslessly — guaranteed by the bit-width
/// constraint since `$B::MAX > 0` and unsigned `$A` can hold any
/// positive value up to `$A::MAX ≥ $B::MAX`. `inner` casts
/// non-negative `$B` values to `$A`, also lossless under the
/// same constraint. Mirrors the `ext_int!` constraint pattern.
///
/// **Right-Galois single-sided** (uses [`Conn::new_right`](crate::conn::Conn::new_right)). The
/// saturation plateau lives on the target side: `inner` clips
/// `i_M`'s negative half to `0_u_N`. `floor` saturates `u_N` values
/// above `i_M::MAX` down to `i_M::MAX`.
///
/// No FINE_MAX fixup needed: `inner`'s image is exactly
/// `[0, i_M::MAX as u_N]`, and `floor`'s collapse at the high
/// plateau aligns the target-side fiber with the source identity at
/// `i_M::MAX`.
macro_rules! uint_int_sat {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating cast (right-Galois).")]
        pub const $NAME: Conn<$A, $B> = {
            fn floor(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x < 0 { 0 } else { x as $A }
            }
            Conn::new_right(inner, floor)
        };
    };
}
pub(crate) use uint_int_sat;

/// `Conn<Extended<i<N>>, NonZero<i<N>>>` — saturate `Extended<iN>` onto
/// `NonZero<iN>`, with `floor` and `ceil` differing at `Finite(0)`
/// (the asymmetric-adjoint showcase: there is no NonZero `= 0`, so
/// `floor` rounds to `-1` and `ceil` rounds to `+1`).
///
/// Forward (`ceil` / `floor`): `Extended<iN> → NonZero<iN>`.
///
/// - `NegInf  → NonZero(<iN>::MIN)`  (both ceil and floor saturate)
/// - `PosInf  → NonZero(<iN>::MAX)`
/// - `Finite(v != 0) → NonZero(v)` (lossless on both adjoints)
/// - `floor(Finite(0)) → NonZero(-1)` (largest NonZero ≤ 0)
/// - `ceil(Finite(0))  → NonZero(+1)` (smallest NonZero ≥ 0)
///
/// Back (`inner`): trivial total embedding
/// `NonZero<iN> → Extended<iN>::Finite(.get())`.
///
/// Both Galois laws (`conn_galois_l` and `conn_galois_r`) hold,
/// because the asymmetric `floor`/`ceil` lift the punctured target's
/// "missing zero" to a sandwich [-1, +1] at the source-side zero.
macro_rules! nz_int_ext {
    ($NAME:ident, $A:ty, $NZ:ty) => {
        #[doc = concat!(
            "`Extended<", stringify!($A), "> ↔ ", stringify!($NZ),
            "` (signed; floor/ceil split `Finite(0)` between -1 and +1)."
        )]
        pub const $NAME: Conn<Extended<$A>, $NZ> = {
            fn ceil(x: Extended<$A>) -> $NZ {
                let r: $A = match x {
                    Extended::NegInf => <$A>::MIN,
                    Extended::PosInf => <$A>::MAX,
                    Extended::Finite(v) => {
                        if v == 0 {
                            1
                        } else {
                            v
                        }
                    }
                };
                <$NZ>::new(r).expect("nz_int_ext::ceil produced zero")
            }
            fn floor(x: Extended<$A>) -> $NZ {
                let r: $A = match x {
                    Extended::NegInf => <$A>::MIN,
                    Extended::PosInf => <$A>::MAX,
                    Extended::Finite(v) => {
                        if v == 0 {
                            -1
                        } else {
                            v
                        }
                    }
                };
                <$NZ>::new(r).expect("nz_int_ext::floor produced zero")
            }
            fn inner(nz: $NZ) -> Extended<$A> {
                Extended::Finite(nz.get())
            }
            Conn::new(ceil, inner, floor)
        };
    };
}
pub(crate) use nz_int_ext;

/// `Conn<Extended<u<N>>, NonZero<u<N>>>` — unsigned counterpart of
/// [`nz_int_ext!`]. `floor` and `ceil` saturate uniformly because
/// there is no NonZero `≤ 0` on the unsigned side: both `Finite(0)`
/// and `NegInf` collapse to `NonZero(1)`. Single-sided left-Galois
/// ([`Conn::new_left`]) — `floor = ceil`.
///
/// [`Conn::new_left`]: crate::conn::Conn::new_left
macro_rules! nz_uint_ext {
    ($NAME:ident, $A:ty, $NZ:ty) => {
        #[doc = concat!(
            "`Extended<", stringify!($A), "> ↔ ", stringify!($NZ),
            "` (unsigned; `Finite(0)` and `NegInf` saturate to NonZero(1))."
        )]
        pub const $NAME: Conn<Extended<$A>, $NZ> = {
            fn ceil(x: Extended<$A>) -> $NZ {
                let r: $A = match x {
                    Extended::NegInf => 1,
                    Extended::PosInf => <$A>::MAX,
                    Extended::Finite(v) => {
                        if v == 0 {
                            1
                        } else {
                            v
                        }
                    }
                };
                <$NZ>::new(r).expect("nz_uint_ext::ceil produced zero")
            }
            fn inner(nz: $NZ) -> Extended<$A> {
                Extended::Finite(nz.get())
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use nz_uint_ext;

/// `Conn<i_N, u_M>` narrowing (`bits(i_N) > bits(u_M)`).
///
/// `ceil` clips negatives to `0` and saturates positives at
/// `u_M::MAX`; `inner` is the lossless `as`-widen with a FINE_MAX
/// fixup (`inner(u_M::MAX) = i_N::MAX`). The negative half of the
/// source has no plateau issue (it collapses on `ceil`, the
/// source-side fiber compatible with left-Galois).
macro_rules! int_uint_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x < 0 {
                    0
                } else if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            Conn::new_left(ceil, inner)
        };
    };
}
pub(crate) use int_uint_narrow;

// ── Per-primitive submodules ───────────────────────────────────────

pub mod i128;
pub mod i16;
pub mod i32;
pub mod i64;
pub mod i8;
pub mod u128;
pub mod u16;
pub mod u32;
pub mod u64;
pub mod u8;
