//! Connections among **fixed-point types** — Q-format wrappers from
//! the [`fixed`] crate, std primitive integers (interpreted as
//! Q*N*.0 fixed-point), and [`core::num::NonZero<T>`] (punctured
//! Q*N*.0). The float/fixed split between [`crate::float`] and this
//! module is the crate's only top-level domain distinction:
//! everything finite-precision-with-integer-storage lives here;
//! every IEEE-binary type lives in [`crate::float`].
//!
//! [`fixed`]: https://docs.rs/fixed
//! [`core::num::NonZero<T>`]: https://doc.rust-lang.org/core/num/struct.NonZero.html
//!
//! ## Submodules
//!
//! - [`mod@i008`] / [`mod@i016`] / [`mod@i032`] / [`mod@i064`] / [`mod@i128`] —
//!   signed-source std-int Conns plus signed `FixedI<N><Frac>` and
//!   `NonZeroI<N>` host surfaces.
//! - [`mod@u008`] / [`mod@u016`] / [`mod@u032`] / [`mod@u064`] / [`mod@u128`] —
//!   unsigned-source std-int Conns plus unsigned `FixedU<N><Frac>` and
//!   `NonZeroU<N>` host surfaces.
//!
//! ## Example
//!
//! ```rust
//! use connections::conn::ConnR;
//! use connections::fixed::u032::U032I032;
//!
//! // u32 PID into i32 — saturates instead of wrapping for large values.
//! assert_eq!(U032I032.floor(1_u32), 1_i32);
//! assert_eq!(U032I032.floor((i32::MAX as u32) + 1), i32::MAX);
//! assert_eq!(U032I032.floor(u32::MAX), i32::MAX);
//! ```
//!
//! ## Conn-name prefix conventions (post-merge)
//!
//! After the `int/` ⊕ `fixed/` merge, the prefix letter alone tells
//! you which world a side belongs to:
//!
//! | Prefix | Shape | Side meaning                                            |
//! |--------|-------|---------------------------------------------------------|
//! | `Q`    | 1L+3D | `FixedI<N>` / `FixedU<N>` (Q-format). Sign implicit by module path; digits = frac bits. |
//! | `I`    | 1L+3D | signed std primitive (`iN`). Digits = bit-width.        |
//! | `U`    | 1L+3D | unsigned std primitive (`uN`). Digits = bit-width.      |
//! | `N`    | 1L+3D | `NonZero<iN>` / `NonZero<uN>`. Sign implicit by module path; digits = bit-width. |
//!
//! Cross-module name collisions (e.g. `Q008Q004` in both
//! [`mod@i008`] and [`mod@u008`]) are allowed and resolved by qualified
//! import.
//!
//! ## Macros
//!
//! Seven macro families generate the std-int Conns; all live in this
//! parent module and are `pub(crate)`-imported by the per-primitive
//! submodules:
//!
//! | macro | direction | Galois | constructor |
//! |---|---|---|---|
//! | `uint_uint!`        | U→U widening    | left  | `new_l` |
//! | `int_uint!`         | I→U widening    | left  | `new_l` |
//! | `ext_int!`          | I→I, U→I widening (Extended source) | left  | `new_l` |
//! | `int_int_narrow!`   | I→I narrowing   | left  | `new_l` |
//! | `uint_uint_narrow!` | U→U narrowing   | left  | `new_l` |
//! | `int_uint_narrow!`  | I→U narrowing   | left  | `new_l` |
//! | `uint_int_sat!`     | U→I non-widening | right | `new_r` |
//!
//! The four narrowing/non-widening macros use a **FINE_MAX
//! boundary fixup** in `inner` (`inner(Coarse::MAX) =
//! Source::MAX`) so the relevant Galois bi-implication holds at
//! the source-side saturation plateau — same pattern as the
//! per-primitive `fix_fix_uN!` macros below. The right-Galois
//! `uint_int_sat!` macro doesn't need the fixup: its plateau lives
//! on the target side (negative `i_N` values clip to `0_u_M` via
//! `inner`), and `floor` collapses the symmetric way at the high
//! end.
//!
//! The intra-`fixed`-crate Conns are generated by per-primitive
//! `fix_fix_iN!` / `fix_fix_uN!` macros, each defined locally in its
//! per-host-type submodule (`fixed/i008.rs` etc.).
//!
//! The `fixed`-crate `FixedI<N><F>` / `FixedU<N><F>` types already
//! derive `PartialEq` / `Eq` / `PartialOrd` / `Ord` upstream —
//! totally ordered by their underlying integer bits — so they flow
//! through any `T: Eq + PartialOrd` law predicate without per-crate
//! impls.

// The macros expand at the call site (in each submodule), so this
// parent file doesn't need to import `Conn` or `Extended` itself —
// the submodules pull them in.

/// Little-endian byte array wrapper with numeric-sort ordering.
///
/// Plain `[u8; N]` uses lexicographic order from index 0 upward, which
/// makes big-endian byte arrays sortable but breaks little-endian numeric
/// order for multi-byte widths. `LE<N>` keeps the little-endian storage
/// shape while ordering from the most-significant byte down to the
/// least-significant byte.
#[repr(transparent)]
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub struct LE<const N: usize>(pub [u8; N]);

impl<const N: usize> Ord for LE<N> {
    #[inline]
    fn cmp(&self, other: &Self) -> core::cmp::Ordering {
        self.0.iter().rev().cmp(other.0.iter().rev())
    }
}

impl<const N: usize> PartialOrd for LE<N> {
    #[inline]
    fn partial_cmp(&self, other: &Self) -> Option<core::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl<const N: usize> From<[u8; N]> for LE<N> {
    #[inline]
    fn from(bytes: [u8; N]) -> Self {
        Self(bytes)
    }
}

impl<const N: usize> From<LE<N>> for [u8; N] {
    #[inline]
    fn from(bytes: LE<N>) -> Self {
        bytes.0
    }
}

impl<const N: usize> AsRef<[u8; N]> for LE<N> {
    #[inline]
    fn as_ref(&self) -> &[u8; N] {
        &self.0
    }
}

#[cfg(test)]
mod le_tests {
    use super::LE;

    #[test]
    fn le_order_compares_most_significant_byte_first() {
        assert!(LE([1]) < LE([2]));
        assert!(LE([1, 0]) < LE([2, 0]));
        assert!(LE([255, 0]) < LE([0, 1]));
        assert!(LE([255, 255, 0, 0]) < LE([0, 0, 1, 0]));
    }

    #[test]
    fn le_equality_matches_inner_bytes() {
        assert_eq!(LE([1, 2, 3, 4]), LE([1, 2, 3, 4]));
        assert_ne!(LE([1, 2, 3, 4]), LE([1, 2, 3, 5]));
    }
}

// ── std-int macros (lifted from former src/int.rs) ─────────────────

/// `Conn<u_N, u_M>` widening (`bits(u_N) < bits(u_M)`).
///
/// `ceil` is the lossless `as`-upcast; `inner` saturates targets
/// above `u_N::MAX` down to `u_N::MAX` before downcasting.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! uint_uint {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating cast.")]
        pub const $NAME: $crate::conn::Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                x as $B
            }
            fn inner(x: $B) -> $A {
                let cap = <$A>::MAX as $B;
                let clipped = if x > cap { cap } else { x };
                clipped as $A
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use uint_uint;

/// `Conn<i_N, u_M>` widening or same-width cross-sign
/// (`bits(i_N) ≤ bits(u_M)`).
///
/// `ceil` clips negatives to `0` then upcasts (lossless on the
/// non-negative half by the bit-width constraint); `inner`
/// saturates targets above `i_N::MAX` down to `i_N::MAX`.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! int_uint {
    ($NAME:ident, $A:ty, $B:ty) => {
        // rustfmt's indent-instability bug with `#[doc = concat!(...)]`
        // means each fmt round pushes the args further right.
        // `#[rustfmt::skip]` pins the layout. See ext_int! below for
        // the same workaround.
#[rustfmt::skip]
        #[doc = concat!(
            "`",
            stringify!($A),
            " → ",
            stringify!($B),
            "` saturating cast: negatives clip to 0; `inner` saturates at source max."
        )]
        pub const $NAME: $crate::conn::Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x < 0 { 0 } else { x as $B }
            }
            fn inner(x: $B) -> $A {
                let cap = <$A>::MAX as $B;
                let clipped = if x > cap { cap } else { x };
                clipped as $A
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use int_uint;

/// `Conn<Extended<$A>, $B>` widening with Extended source (left-Galois).
/// Covers both `I??I??` (signed widening) and `U??I??`
/// (unsigned-into-signed widening) — the body is identical, only
/// the source's `MIN`/`MAX` differ.
///
/// Constraints (verified at the call site, not at compile time):
/// - `(<$A>::MIN as $B) - 1` and `(<$A>::MAX as $B) + 1` must fit
///   in `$B` — guaranteed by `bits($A) < bits($B)` (signed source)
///   or `bits($A) ≤ bits($B) - 1` (unsigned source, equivalent).
/// - `<$B>::MIN < BELOW` and `<$B>::MAX > ABOVE` (i.e. target has
///   room beyond the source range so saturation values are
///   distinct).
///
/// **One-sided.** `_inner` collapses every rung value `≤ BELOW` onto
/// `Extended::NegInf` and every rung value `≥ ABOVE` onto
/// `Extended::PosInf` — non-injective at the saturation regions, so
/// not order-reflecting, so no true adjoint triple exists. The
/// L-Galois adjunction `ceil ⊣ inner` holds on the full domain;
/// shipped as `ConnL` accordingly. (Plan 32.)
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! ext_int {
    ($NAME:ident, $A:ty, $B:ty) => {
#[rustfmt::skip]
        #[doc = concat!(
            "`Extended<",
            stringify!($A),
            "> → ",
            stringify!($B),
            "` left-Galois widening."
        )]
        pub const $NAME: $crate::conn::Conn<$crate::extended::Extended<$A>, $B> = {
            const BELOW: $B = (<$A>::MIN as $B) - 1;
            const ABOVE: $B = (<$A>::MAX as $B) + 1;
            fn ceil(x: $crate::extended::Extended<$A>) -> $B {
                match x {
                    $crate::extended::Extended::NegInf => <$B>::MIN,
                    $crate::extended::Extended::Finite(a) => a as $B,
                    $crate::extended::Extended::PosInf => ABOVE,
                }
            }
            fn inner(x: $B) -> $crate::extended::Extended<$A> {
                if x <= BELOW {
                    $crate::extended::Extended::NegInf
                } else if x >= ABOVE {
                    $crate::extended::Extended::PosInf
                } else {
                    $crate::extended::Extended::Finite(x as $A)
                }
            }

            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use ext_int;

// ── Narrowing macros ───────────────────────────────────────────────

/// `Conn<i_N, i_M>` narrowing (`bits(i_N) > bits(i_M)`).
///
/// **Constraint** (verified at the call site, not at compile time):
/// `bits($A) > bits($B)`. The macro's `ceil` casts `<$B>::MAX as $A`
/// and `<$B>::MIN as $A` for its threshold checks; both must fit
/// losslessly in `$A` for the saturation logic to be correct.
/// Mirrors the `ext_int!` constraint a few lines up.
///
/// `ceil` saturates at both `i_M::MIN` and `i_M::MAX`; `inner` is
/// the lossless widen with the high-end FINE_MAX fixup
/// (`inner(i_M::MAX) = i_N::MAX`).
///
/// **Why no FINE_MIN fixup?** The low-end plateau holds for
/// `galois_l` without one. The plateau covers source values
/// `a < i_M::MIN as i_N` (everything `ceil` collapses onto
/// `i_M::MIN`). For these, `ceil(a) = i_M::MIN ≤ b` is true for
/// every `b ∈ i_M`, so the law's LHS is always true, and the RHS
/// (`a ≤ inner(b)`) is also always true because
/// `inner(b) ≥ i_M::MIN as i_N > a` (since
/// `i_M::MIN as i_N > i_N::MIN ≥ a` by the bit-width
/// constraint). Both sides match without fiddling. Compare the
/// high end, where `ceil` collapsing onto `i_M::MAX` does require
/// the fixup so `a ≤ inner(i_M::MAX) = i_N::MAX` holds.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! int_int_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: $crate::conn::Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else if x < <$B>::MIN as $A {
                    <$B>::MIN
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use int_int_narrow;

/// `Conn<u_N, u_M>` narrowing (`bits(u_N) > bits(u_M)`).
///
/// `ceil` saturates source values above `u_M::MAX` down to
/// `u_M::MAX` before downcasting. There is **no** low-end branch
/// (no `MIN` saturation arm) because both endpoints are unsigned —
/// the source range starts at `0 = u_N::MIN ≥ u_M::MIN = 0`, so no
/// source value can fall below the target's minimum. Compare
/// `int_int_narrow!`, which needs both arms because signed sources
/// can dip below the target's `MIN`.
///
/// `inner` is the lossless `as`-widen with a FINE_MAX fixup
/// (`inner(u_M::MAX) = u_N::MAX`). The fixup is required for
/// left-Galois to hold at the source-side saturation plateau
/// (mirrors the same pattern in the per-primitive `fix_fix_uN!`
/// macros).
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! uint_uint_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: $crate::conn::Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use uint_uint_narrow;

/// `Conn<u_N, i_M>` non-widening cross-sign (`bits(u_N) ≥ bits(i_M)`).
///
/// **Constraint** (verified at the call site, not at compile time):
/// `bits($A) ≥ bits($B)`. `floor` casts `<$B>::MAX as $A`, which
/// must fit in `$A` losslessly — guaranteed by the bit-width
/// constraint since `$B::MAX > 0` and unsigned `$A` can hold any
/// positive value up to `$A::MAX ≥ $B::MAX`. `inner` casts
/// non-negative `$B` values to `$A`, also lossless under the
/// same constraint. Mirrors the `ext_int!` constraint pattern.
///
/// **Right-Galois single-sided** (uses [`Conn::new_r`](crate::conn::Conn::new_r)). The
/// saturation plateau lives on the target side: `inner` clips
/// `i_M`'s negative half to `0_u_N`. `floor` saturates `u_N` values
/// above `i_M::MAX` down to `i_M::MAX`.
///
/// No FINE_MAX fixup needed: `inner`'s image is exactly
/// `[0, i_M::MAX as u_N]`, and `floor`'s collapse at the high
/// plateau aligns the target-side fiber with the source identity at
/// `i_M::MAX`.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! uint_int_sat {
    ($(#[$attr:meta])* $NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating cast (right-Galois).")]
        $(#[$attr])*
        pub const $NAME: $crate::conn::Conn<$A, $B, $crate::conn::R> = {
            fn floor(x: $A) -> $B {
                if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x < 0 { 0 } else { x as $A }
            }
            $crate::conn::Conn::new_r(inner, floor)
        };
    };
}
pub(crate) use uint_int_sat;

/// `Conn<i<N>, NonZero<i<N>>>` — saturate `iN` onto `NonZero<iN>` with
/// asymmetric rounding at zero. Source is the bare primitive (not
/// `Extended<iN>`) so there are no infinities at the source-side
/// plateau to break the Galois law: every `iN` value other than 0 is
/// itself a `NonZero<iN>`, and 0 sandwiches between `NonZero(-1)` and
/// `NonZero(+1)`.
///
/// Forward (`ceil` / `floor`): `iN → NonZero<iN>`.
///
/// - `floor(0) = NonZero(-1)`  (largest NonZero ≤ 0)
/// - `ceil(0)  = NonZero(+1)`  (smallest NonZero ≥ 0)
/// - For `v != 0`: `ceil(v) = floor(v) = NonZero(v)` (lossless).
///
/// Back (`inner`): trivial total embedding
/// `NonZero<iN> → iN::get()`.
///
/// Both Galois laws (`galois_l` and `galois_r`) hold: the
/// asymmetric `floor`/`ceil` lift the target's puncture at zero to a
/// [-1, +1] sandwich on the source side, exactly bracketing the
/// missing value.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! nz_int_ext {
    ($NAME:ident, $A:ty, $NZ:ty) => {
#[rustfmt::skip]
        #[doc = concat!(
            "`",
            stringify!($A),
            " ↔ ",
            stringify!($NZ),
            "` (signed; floor/ceil split 0 between -1 and +1)."
        )]
        pub struct $NAME;

        impl $NAME {
            const fn _ceil(v: $A) -> $NZ {
                let r: $A = if v == 0 { 1 } else { v };
                match <$NZ>::new(r) {
                    Some(nz) => nz,
                    None => panic!("nz_int_ext::ceil produced zero"),
                }
            }
            const fn _floor(v: $A) -> $NZ {
                let r: $A = if v == 0 { -1 } else { v };
                match <$NZ>::new(r) {
                    Some(nz) => nz,
                    None => panic!("nz_int_ext::floor produced zero"),
                }
            }
            const fn _inner(nz: $NZ) -> $A {
                nz.get()
            }
        }

        impl $crate::conn::ConnL<$A, $NZ> for $NAME {
            #[inline]
            fn conn_l(&self) -> $crate::conn::Conn<$A, $NZ, $crate::conn::L> {
                $crate::conn::Conn::new_l($NAME::_ceil, $NAME::_inner)
            }
        }
        impl $crate::conn::ConnR<$A, $NZ> for $NAME {
            #[inline]
            fn conn_r(&self) -> $crate::conn::Conn<$A, $NZ, $crate::conn::R> {
                $crate::conn::Conn::new_r($NAME::_inner, $NAME::_floor)
            }
        }
    };
}
pub(crate) use nz_int_ext;

/// `Conn<u<N>, NonZero<u<N>>>` — unsigned counterpart of
/// [`nz_int_ext!`]. `floor` and `ceil` collapse identically at 0
/// because there is no NonZero ≤ 0 on the unsigned side: both pick
/// `NonZero(1)`, the smallest representable NonZero. Single-sided
/// left-Galois ([`Conn::new_l`]) — `floor = ceil`. The
/// right-Galois law fails at `(NonZero(1), 0)` (no NonZero strictly
/// below 1 to act as the "previous" rounding target).
///
/// [`Conn::new_l`]: crate::conn::Conn::new_l
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! nz_uint_ext {
    ($NAME:ident, $A:ty, $NZ:ty) => {
#[rustfmt::skip]
        #[doc = concat!(
            "`",
            stringify!($A),
            " ↔ ",
            stringify!($NZ),
            "` (unsigned; 0 saturates to NonZero(1); single-sided left-Galois)."
        )]
        pub const $NAME: $crate::conn::Conn<$A, $NZ> = {
            fn ceil(v: $A) -> $NZ {
                let r: $A = if v == 0 { 1 } else { v };
                match <$NZ>::new(r) {
                    Some(nz) => nz,
                    None => panic!("nz_uint_ext::ceil produced zero"),
                }
            }
            fn inner(nz: $NZ) -> $A {
                nz.get()
            }

            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use nz_uint_ext;

/// `Conn<i_N, u_M>` narrowing (`bits(i_N) > bits(u_M)`).
///
/// `ceil` clips negatives to `0` and saturates positives at
/// `u_M::MAX`; `inner` is the lossless `as`-widen with a FINE_MAX
/// fixup (`inner(u_M::MAX) = i_N::MAX`). The negative half of the
/// source has no plateau issue (it collapses on `ceil`, the
/// source-side fiber compatible with left-Galois).
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! int_uint_narrow {
    ($NAME:ident, $A:ty, $B:ty) => {
        #[doc = concat!("`", stringify!($A), " → ", stringify!($B), "` saturating narrow.")]
        pub const $NAME: $crate::conn::Conn<$A, $B> = {
            fn ceil(x: $A) -> $B {
                if x < 0 {
                    0
                } else if x > <$B>::MAX as $A {
                    <$B>::MAX
                } else {
                    x as $B
                }
            }
            fn inner(x: $B) -> $A {
                if x == <$B>::MAX { <$A>::MAX } else { x as $A }
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}
pub(crate) use int_uint_narrow;

// ── Float → Q-format Conn macros ───────────────────────────────────
//
// `float_fixed!` / `float_fixed_l!` parallel `float_ext_int!` /
// `float_ext_int_l!` from `src/float.rs` but target a `fixed`-crate
// `FixedI<host>`/`FixedU<host>` Q-format wrapper instead of a std
// integer. Live here rather than `src/float.rs` because the macro
// body reaches into `fixed::FixedI*`/`FixedU*` types — hosting them
// next to `ext_int!` keeps the fixed-crate dependency on this side.
//
// Saturation policy mirrors `__float_ext_int_*_body!`:
//
// - `ExtendedFloat::Bot`              → `Extended::NegInf`
// - `ExtendedFloat::Top`              → `Extended::PosInf`
// - `Extend(v)` with `v.is_nan()`     → `PosInf` (ceil) / `NegInf` (floor)
// - `Extend(NEG_INFINITY)`            → `Finite(MIN)` (ceil) / `NegInf` (floor)
// - `Extend(INFINITY)`                → `PosInf`
// - `Extend(v)` with `v >  max_v_f64` → `PosInf` (ceil) / `Finite(MAX)` (floor)
// - `Extend(v)` with `v <  min_v_f64` → `Finite(MIN)` (ceil) / `NegInf` (floor)
// - in-range `v`                      → `Finite(<$Fixed<$Frac>>::from_bits((v * 2^F).ceil() as $Bits))`
//                                      / same with `floor()`
//
// `inner` always materialises a finite float for `Finite(q)` and
// emits `Bot`/`Top` for `NegInf`/`PosInf`. The
// round-toward-negative-infinity semantics (via the
// `RoundDownFromF64` dispatch) are L-Galois-correct — round-to-
// nearest-even can over-round and break `ceil(inner(b)) ≤ b`.
//
// All math goes through f64 even for f32/f16 sources: the upcast
// `f as f64` is exact, `2^F` is f64-exact for `F ≤ 1023` (well
// above our `F ≤ 128` rung cadence), and routing through f64
// sidesteps the f32 `2^128` overflow.

#[doc(hidden)]
#[macro_export]
macro_rules! __float_fix_ceil_body {
    ($float:ty, $Fixed:ident, $Frac:ty, $Bits:ty, $v:ident) => {{
        // NaN: incomparable with finite Extend(_); ≤ Top in N5 →
        // smallest b such that upper(b) ≥ NaN is PosInf.
        if $v.is_nan() {
            $crate::extended::Extended::PosInf
        } else if $v == <$float>::INFINITY {
            // Explicit +∞ guard — for f16 sources targeting
            // wide-host Q-formats (`<$Bits>::MAX as f16` saturates
            // to +∞), the unified `v > max_v_f64` branch can't
            // distinguish +∞ from saturated `max_v_f64`.
            $crate::extended::Extended::PosInf
        } else {
            let v_f64: f64 = $v as f64;
            let max_q: $Fixed<$Frac> = <$Fixed<$Frac>>::MAX;
            let min_q: $Fixed<$Frac> = <$Fixed<$Frac>>::MIN;
            let max_v_f64: f64 = max_q.to_num::<f64>();
            let min_v_f64: f64 = min_q.to_num::<f64>();
            if v_f64 > max_v_f64 {
                $crate::extended::Extended::PosInf
            } else if v_f64 < min_v_f64 {
                $crate::extended::Extended::Finite(min_q)
            } else {
                let scale: f64 =
                    $crate::float::scale_pow2_f64(<$Frac as ::fixed::types::extra::Unsigned>::U32);
                let scaled: f64 = v_f64 * scale;
                let scaled_ceil: f64 = scaled.ceil();
                let bits: $Bits = scaled_ceil as $Bits;
                // Boundary-saturation overflow detection: when
                // `<$Bits>::MAX` rounds up in f64 (host bits > 53),
                // the strict `v_f64 > max_v_f64` guard above misses
                // the case where `v_f64 == max_v_f64` while
                // `real_v > real_max`. The saturating cast pinned
                // `bits` to MAX; verify via the round-down image
                // of MAX whether the cast actually overflowed.
                // For hosts where MAX is f64-exact (host bits ≤ 53,
                // and signed 128-bit), `to_f64_rd(MAX) == max_v_f64`
                // and this check is a no-op — `scaled_ceil` ≤
                // `max_v_f64` in the in-range branch by construction.
                if bits == <$Bits>::MAX
                    && <$Bits as $crate::float::BitsToF64Rd>::to_f64_rd(<$Bits>::MAX) < scaled_ceil
                {
                    $crate::extended::Extended::PosInf
                } else {
                    $crate::extended::Extended::Finite(<$Fixed<$Frac>>::from_bits(bits))
                }
            }
        }
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __float_fix_floor_body {
    ($float:ty, $Fixed:ident, $Frac:ty, $Bits:ty, $v:ident) => {{
        if $v.is_nan() {
            $crate::extended::Extended::NegInf
        } else {
            let v_f64: f64 = $v as f64;
            let max_q: $Fixed<$Frac> = <$Fixed<$Frac>>::MAX;
            let min_q: $Fixed<$Frac> = <$Fixed<$Frac>>::MIN;
            let max_v_f64: f64 = max_q.to_num::<f64>();
            let min_v_f64: f64 = min_q.to_num::<f64>();
            if v_f64 > max_v_f64 {
                $crate::extended::Extended::Finite(max_q)
            } else if v_f64 < min_v_f64 {
                $crate::extended::Extended::NegInf
            } else {
                let scale: f64 =
                    $crate::float::scale_pow2_f64(<$Frac as ::fixed::types::extra::Unsigned>::U32);
                let scaled: f64 = v_f64 * scale;
                let bits: $Bits = scaled.floor() as $Bits;
                $crate::extended::Extended::Finite(<$Fixed<$Frac>>::from_bits(bits))
            }
        }
    }};
}

#[doc(hidden)]
#[macro_export]
macro_rules! __float_fix_inner_body {
    ($float:ty, $Fixed:ident, $Frac:ty, $Bits:ty, $b:ident) => {
        // Map `Extended` sentinels to matching `ExtendedFloat`
        // sentinels. Same N5-ordering reasoning as
        // `__float_ext_int_inner_body!`: emitting `Extend(±INFINITY)`
        // here would break Galois at `(Top, PosInf)` /
        // `(Bot, NegInf)` boundaries.
        //
        // Finite arm: round-toward-negative-infinity via f64
        // intermediate. The host-bits-to-f64 dispatch uses
        // [`BitsToF64Rd`](crate::float::BitsToF64Rd) so the u128
        // host's top-end saturation (where `u128::MAX as f64` rounds
        // up to `2^128`) is handled correctly — naive `q.to_bits()
        // as i128` would wrap for `bits > i128::MAX` and break
        // L-Galois at the high plateau.
        match $b {
            $crate::extended::Extended::NegInf => $crate::float::ExtendedFloat::Bot,
            $crate::extended::Extended::PosInf => $crate::float::ExtendedFloat::Top,
            $crate::extended::Extended::Finite(q) => {
                let approx_f64: f64 = <$Bits as $crate::float::BitsToF64Rd>::to_f64_rd(q.to_bits());
                let scale_neg: f64 = $crate::float::scale_pow2_f64_neg(
                    <$Frac as ::fixed::types::extra::Unsigned>::U32,
                );
                let value_f64: f64 = approx_f64 * scale_neg;
                let value: $float =
                    <$float as $crate::float::RoundDownFromF64>::from_f64_rd(value_f64);
                $crate::float::ExtendedFloat::Extend(value)
            }
        }
    };
}

/// Emit a full adjoint-triple Conn `Conn<ExtendedFloat<$float>,
/// Extended<$Fixed<$Frac>>>` (impls `ConnL` + `ConnR`) via
/// [`conn_k!`](crate::conn_k).
///
/// Use when `<$Bits>::BITS ≤ <$float>::MANTISSA_DIGITS` so that
/// every Q-format value embeds losslessly into the source float —
/// only then is `inner` order-reflecting.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! float_fixed {
    ($(#[$meta:meta])* $vis:vis $name:ident, $float:ty, $Fixed:ident, $Frac:ty, $Bits:ty) => {
        $crate::conn_k! {
            $(#[$meta])*
            $vis $name : $crate::float::ExtendedFloat<$float> => $crate::extended::Extended<$Fixed<$Frac>> {
                ceil:  {
                    fn ceil(x: $crate::float::ExtendedFloat<$float>)
                        -> $crate::extended::Extended<$Fixed<$Frac>>
                    {
                        match x {
                            $crate::float::ExtendedFloat::Bot => $crate::extended::Extended::NegInf,
                            $crate::float::ExtendedFloat::Top => $crate::extended::Extended::PosInf,
                            $crate::float::ExtendedFloat::Extend(v) =>
                                $crate::__float_fix_ceil_body!($float, $Fixed, $Frac, $Bits, v),
                        }
                    }
                    ceil
                },
                inner: {
                    fn inner(b: $crate::extended::Extended<$Fixed<$Frac>>)
                        -> $crate::float::ExtendedFloat<$float>
                    {
                        $crate::__float_fix_inner_body!($float, $Fixed, $Frac, $Bits, b)
                    }
                    inner
                },
                floor: {
                    fn floor(x: $crate::float::ExtendedFloat<$float>)
                        -> $crate::extended::Extended<$Fixed<$Frac>>
                    {
                        match x {
                            $crate::float::ExtendedFloat::Bot => $crate::extended::Extended::NegInf,
                            $crate::float::ExtendedFloat::Top => $crate::extended::Extended::PosInf,
                            $crate::float::ExtendedFloat::Extend(v) =>
                                $crate::__float_fix_floor_body!($float, $Fixed, $Frac, $Bits, v),
                        }
                    }
                    floor
                },
            }
        }
    };
}

/// Emit an L-only Conn `Conn<ExtendedFloat<$float>,
/// Extended<$Fixed<$Frac>>, L>`.
///
/// Use when `<$Bits>::BITS > <$float>::MANTISSA_DIGITS` so that
/// `inner` aliases distinct Q-format values onto the same float at
/// large magnitudes — the L-Galois adjunction `ceil ⊣ inner` still
/// holds, but `order_reflecting` does not.
#[cfg_attr(feature = "macros", macro_export)]
macro_rules! float_fixed_l {
    ($(#[$meta:meta])* $vis:vis $name:ident, $float:ty, $Fixed:ident, $Frac:ty, $Bits:ty) => {
        $(#[$meta])*
        $vis const $name: $crate::conn::Conn<
            $crate::float::ExtendedFloat<$float>,
            $crate::extended::Extended<$Fixed<$Frac>>,
        > = {
            fn ceil(x: $crate::float::ExtendedFloat<$float>)
                -> $crate::extended::Extended<$Fixed<$Frac>>
            {
                match x {
                    $crate::float::ExtendedFloat::Bot => $crate::extended::Extended::NegInf,
                    $crate::float::ExtendedFloat::Top => $crate::extended::Extended::PosInf,
                    $crate::float::ExtendedFloat::Extend(v) =>
                        $crate::__float_fix_ceil_body!($float, $Fixed, $Frac, $Bits, v),
                }
            }
            fn inner(b: $crate::extended::Extended<$Fixed<$Frac>>)
                -> $crate::float::ExtendedFloat<$float>
            {
                $crate::__float_fix_inner_body!($float, $Fixed, $Frac, $Bits, b)
            }
            $crate::conn::Conn::new_l(ceil, inner)
        };
    };
}

pub(crate) use float_fixed;
pub(crate) use float_fixed_l;

// ── Per-primitive submodules ───────────────────────────────────────

pub mod i008;
pub mod i016;
pub mod i032;
pub mod i064;
pub mod i128;
pub mod u008;
pub mod u016;
pub mod u032;
pub mod u064;
pub mod u128;
