name: doc-all-features-nightly

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  doc-nightly:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly doc --no-deps --all-features --document-private-items
