name: Kani

on:
  push:
    tags: ['*']
  schedule:
    - cron: '0 5 * * 0'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  kani:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.88.0
      - uses: model-checking/kani-github-action@v1.1
        with:
          args: '--features fixed,hifi,uhlc'
